# Generated by Django 2.1.4 on 2019-02-04 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import obrisk.classifieds.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Expired')], default='A', max_length=1)),
                ('details', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('city', models.CharField(max_length=100)),
                ('located_area', models.CharField(max_length=100)),
                ('total_views', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('edited', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classified',
                'verbose_name_plural': 'Classifieds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ClassifiedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', obrisk.classifieds.models.CloudinaryFieldFix(max_length=255, verbose_name='image')),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.Classified')),
            ],
        ),
    ]
