# Generated by Django 2.1.2 on 2019-06-14 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Expired')], default='A', max_length=1)),
                ('details', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('located_area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province_region', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=100)),
                ('total_views', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('edited', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Classified',
                'verbose_name_plural': 'Classifieds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ClassifiedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('image_thumb', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=2000)),
                ('located_area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province_region', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=150, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'OfficialAd',
                'verbose_name_plural': 'OfficialAds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='OfficialAdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('official_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.OfficialAd')),
            ],
        ),
    ]
