# Generated by Django 2.1.3 on 2018-11-22 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
