# Generated by Django 2.1.4 on 2019-02-05 05:29

from django.db import migrations
import obrisk.classifieds.models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedimages',
            name='image',
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='images',
            field=obrisk.classifieds.models.CloudinaryFieldFix(default='No images', max_length=255, verbose_name='images'),
            preserve_default=False,
        ),
    ]
