# Generated by Django 2.1.2 on 2019-06-14 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='classified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.Classified'),
        ),
        migrations.AddField(
            model_name='classified',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='classified',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
