# Generated by Django 2.1.4 on 2019-02-08 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20190208_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
