# Generated by Django 2.1.3 on 2018-11-23 11:05

from django.db import migrations, models
import django.db.models.deletion
import obrisk.classifieds.models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20181122_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=obrisk.classifieds.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='classified',
            name='image',
        ),
        migrations.AddField(
            model_name='classified',
            name='located_area',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='classified',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='classified',
            name='content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='classified',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='Classified',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classified_images', to='classifieds.Classified'),
        ),
    ]
