# Generated by Django 2.1.4 on 2018-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20181122_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='District',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='classified',
            name='city',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='classified',
            name='located_area',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='classified',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='classified',
            name='street_area',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='classified',
            name='total_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classified',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classified',
            name='content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='classified',
            name='image',
            field=models.ImageField(upload_to='classified_pictures/%Y/%m/%d/', verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='classified',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1),
        ),
    ]
