# Generated by Django 2.1.4 on 2019-02-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_classified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='province_region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
