# Generated by Django 2.1.4 on 2018-12-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20181204_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='District',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='classified',
            name='located_area',
        ),
    ]
