# Generated by Django 2.1.4 on 2019-02-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20190205_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='details',
            field=models.CharField(max_length=1400),
        ),
    ]
