# Generated by Django 2.1.3 on 2018-11-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20181123_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedimages',
            old_name='Classified',
            new_name='classified',
        ),
    ]
