# Generated by Django 2.1.3 on 2018-12-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20181201_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='located_area',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='classified',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='classified',
            name='image',
            field=models.ImageField(upload_to='classified_pictures/%Y/%m/%d/', verbose_name='Featured image'),
        ),
    ]
