# Generated by Django 2.1.4 on 2018-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20181204_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='content',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='classified',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classified',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classified',
            name='street_area',
            field=models.CharField(max_length=100),
        ),
    ]
