# Generated by Django 2.1.4 on 2019-02-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20190208_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classified',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classified',
            name='province_region',
            field=models.CharField(max_length=100),
        ),
    ]
