# Generated by Django 2.1.7 on 2019-03-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20190208_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='contact_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
