# Generated by Django 2.1.4 on 2018-12-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20181204_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
