# Generated by Django 2.1.4 on 2018-12-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_auto_20181204_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='street_area',
            new_name='located_area',
        ),
    ]
