# Generated by Django 2.1.7 on 2019-04-23 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import obrisk.classifieds.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('classifieds', '0007_auto_20190417_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=2000)),
                ('located_area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province_region', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=150, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OfficialAd',
                'verbose_name_plural': 'OfficialAds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='OfficialAdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('official_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.OfficialAd')),
            ],
        ),
    ]
