# Generated by Django 2.1.4 on 2018-12-27 13:32

from django.db import migrations
import imagekit.models.fields
import obrisk.classifieds.models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_auto_20181226_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='displayImage',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to=obrisk.classifieds.models.get_displayImage_filename),
        ),
        migrations.AlterField(
            model_name='classifiedimages',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=obrisk.classifieds.models.get_images_filename),
        ),
        migrations.AlterField(
            model_name='classifiedimages',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to=obrisk.classifieds.models.get_images_filename),
        ),
    ]
