# Generated by Django 2.1.7 on 2019-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_auto_20190504_1602'),
        ('classifieds', '0008_officialad_officialadimages'),
    ]

    operations = [
    ]