# Generated by Django 2.2.3 on 2019-07-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0009_merge_20190510_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classified',
            options={'verbose_name': 'Classified', 'verbose_name_plural': 'Classifieds'},
        ),
    ]
