# Generated by Django 2.1.4 on 2018-12-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0009_auto_20181227_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedimages',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='classifiedimages',
            name='created',
        ),
        migrations.RemoveField(
            model_name='classifiedimages',
            name='height',
        ),
        migrations.RemoveField(
            model_name='classifiedimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='classifiedimages',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='classifiedimages',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='classifiedimages',
            name='width',
        ),
    ]
