# Generated by Django 2.1.7 on 2019-08-09 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0010_auto_20190808_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officialad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
