# Generated by Django 2.1.4 on 2019-01-01 04:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0010_auto_20181229_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='displayImage',
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classifiedimages',
            name='classified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Classified'),
        ),
    ]
