# Generated by Django 2.1.4 on 2019-01-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_auto_20190101_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedimages',
            name='classified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.Classified'),
        ),
    ]
