# Generated by Django 2.1.7 on 2019-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_auto_20190809_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
