# Generated by Django 2.1.4 on 2019-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0012_auto_20190101_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedimages',
            name='image',
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='imageUrl',
            field=models.URLField(default='https://res.cloudinary.com/obrisk/image/upload/c_scale,h_150,w_150/v1546075169/samples/ecommerce/accessories-bag.jpg', max_length=500),
        ),
    ]
