# Generated by Django 2.2.5 on 2019-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0013_auto_20190919_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='located_area',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='classified',
            old_name='contact_info',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='officialad',
            old_name='located_area',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='officialad',
            old_name='contact_info',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='classified',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
