# Generated by Django 2.2.3 on 2019-10-28 10:18

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0014_auto_20191008_1522'),
    ]

    operations = [
        TrigramExtension(),
    ]
