# Generated by Django 2.1.4 on 2019-01-23 12:32

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0014_auto_20190123_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedimages',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
