# Generated by Django 2.1.4 on 2019-01-25 03:15

from django.db import migrations
import obrisk.classifieds.models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0015_auto_20190123_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedimages',
            name='image',
            field=obrisk.classifieds.models.CloudinaryFieldFix(max_length=255, verbose_name='image'),
        ),
    ]
