# Generated by Django 2.2.7 on 2019-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0015_auto_20191028_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='classified',
            name='province_region',
            field=models.CharField(max_length=200),
        ),
    ]
