# Generated by Django 2.1.4 on 2019-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0016_auto_20190125_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='category',
            field=models.CharField(choices=[('A', 'Article'), ('E', 'Event'), ('J', 'Job')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='classified',
            name='status',
            field=models.CharField(choices=[('E', 'Expired'), ('P', 'Active')], default='P', max_length=1),
        ),
    ]
