# Generated by Django 2.2.7 on 2019-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0016_auto_20191118_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedimages',
            name='image_mid_size',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
