# Generated by Django 2.1.4 on 2019-01-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0017_auto_20190125_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='category',
        ),
        migrations.AlterField(
            model_name='classified',
            name='status',
            field=models.CharField(choices=[('E', 'Expired'), ('A', 'Active')], default='A', max_length=1),
        ),
    ]
