# Generated by Django 2.2.9 on 2020-03-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0019_remove_classified_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
