# Generated by Django 2.2.11 on 2021-01-24 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0020_auto_20200306_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='address',
            new_name='english_address',
        ),
        migrations.RemoveField(
            model_name='classified',
            name='total_responses',
        ),
        migrations.RemoveField(
            model_name='classified',
            name='total_views',
        ),
        migrations.AddField(
            model_name='classified',
            name='chinese_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='ClassifiedOrder',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tracking_number', models.CharField(blank=True, max_length=600, null=True)),
                ('chinese_address', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('A', 'Awaiting'), ('C', 'Confirmed'), ('D', 'Dispatched'), ('F', 'Fetched'), ('I', 'Inferred'), ('R', 'Reimbursed'), ('X', 'Axed')], default='A', max_length=1)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True)),
                ('classified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_order', to='classifieds.Classified')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classifieds_Order',
                'verbose_name_plural': 'Classifieds_orders',
                'ordering': ('-timestamp',),
            },
        ),
    ]
