# Generated by Django 2.2.11 on 2021-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0022_auto_20210130_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='handover_method',
            field=models.CharField(choices=[('O', 'Offline_pickup'), ('S', 'Shipping'), ('A', 'any')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='classified',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='classified',
            name='details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
