# Generated by Django 2.2.11 on 2021-04-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0023_auto_20210306_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='bidding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classified',
            name='bids_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classified',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='max_bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='province_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
