# Generated by Django 2.2.11 on 2021-08-31 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210831_2134'),
        ('classifieds', '0024_auto_20210406_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='gif',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classifiedimages',
            name='classified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.Classified'),
        ),
        migrations.CreateModel(
            name='WxClassified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True)),
                ('details', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='users.WechatUser')),
            ],
            options={
                'verbose_name': 'WxClassified',
                'verbose_name_plural': 'WxClassifieds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='wx_classified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.WxClassified'),
        ),
    ]
