  
language: python
dist: bionic
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.2.9
branches:
  only:
    - master
# Start docker services.
services:
  - redis-server
  - postgresql
# command to install dependencies

before_install:
  - pip install -U pip
  - pip install python-coveralls

install:
  - pip install -r requirements/local.txt

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

before_script:
  - psql -c "CREATE DATABASE obdev;" -U postgres
  - cp travis.env .env
  - python manage.py migrate --settings=config.settings.local
  - python manage.py collectstatic --noinput --settings=config.settings.local

# command to run tests
script:
  - pytest
after_success:
  - coveralls

