version: 0.1
os: linux
files:
  - source: /
    destination: /home/obdev-user/obdev2018
permissions:
  - object: /home/obdev-user
    pattern: "**"
    owner: obdev-user
    group: obdev-user 
hooks:
  AfterInstall:
    - location: deploys/python-setup.sh
      timeout: 300
      runas: root

  ApplicationStart:
      - location: deploys/services-restart.sh
        timeout: 300
        runas: root
