version: '3'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    image: postgres:10.3-alpine
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file: .env

  redis:
    image: redis:3.0
    ports:
      - '6379:6379'
