version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}
  redis: {}
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume

networks:  # <-- and here
  nginx_network:
    driver: bridge
  database1_network:  # <-- add the bridge
    driver: bridge
  redis_network:  # <-- add the bridge
    driver: bridge

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    container_name: django
    env_file: .env
    volumes:
      - .:/django/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database1_network
      - redis_network
    depends_on:
      - postgres
      - redis
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:channel_layer

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    networks:
      - database1_network

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./compose/production/nginx/default.conf:/etc/nginx/default.conf
      - static_volume:/django/static  # <-- bind the static volume
      - media_volume:/django/media  # <-- bind the media volume
    depends_on:
      - django
    networks:
      - nginx_network

  redis:
    image: redis:3.0-alpine
    container_name: redis
    env_file: .env
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
    networks:
      -redis_network


