version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}
  redis: {}

networks:  # <-- and here
  nginx_network:
    driver: bridge
  database1_network:  # <-- add the bridge
    driver: bridge
  redis_network:  # <-- add the bridge
    driver: bridge

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    env_file: .env
    networks:
      - nginx_network
      - database1_network
      - redis_network
    depends_on:
      - postgres
      - redis
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:channel_layer

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    networks:
      - database1_network

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - nginx_network

  redis:
    image: redis:3.0-alpine
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
    networks:
      -redis_network


