#it is somehow useless. Just because I saw caddy having Dockerfile, so I wanted to replace it.

FROM nginx:1.13-alpine

# Copy configuration files to the container
COPY ./compose/production/nginx/default.conf /etc/nginx/default.conf