# Generated by Django 2.1.2 on 2019-06-14 12:22

import datetime
from django.db import migrations, models
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=80)),
                ('venue', models.CharField(max_length=80)),
                ('event_image', models.ImageField(upload_to='')),
                ('details', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('contacts', models.CharField(max_length=80)),
                ('sponsors', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('jobs_type', models.CharField(choices=[('FULLTIME', 'full time'), ('PARTTIME', 'part time'), ('INTERNSHIP', 'internship'), ('OTHERS', 'others')], max_length=80)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts_pictures/%Y/%m/%d/', verbose_name='Featured image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
                ('content', markdownx.models.MarkdownxField()),
                ('edited', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-timestamp',),
            },
        ),
    ]
