# Generated by Django 2.1.4 on 2019-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A', 'Article'), ('E', 'Event'), ('J', 'Job')], default='A', max_length=1),
        ),
    ]
