# Generated by Django 2.1.2 on 2019-06-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190614_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ('-posted_date',)},
        ),
    ]
