# Generated by Django 2.1.2 on 2019-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190616_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
