# Generated by Django 2.1.2 on 2019-06-18 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190617_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='contacts',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
