# Generated by Django 2.1.2 on 2019-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190308_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=80)),
                ('venue', models.CharField(max_length=80)),
                ('event_image', models.ImageField(upload_to='')),
                ('details', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('contacts', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('sponsors', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('jobs_type', models.CharField(choices=[('FULLTIME', 'full time'), ('PARTTIME', 'part time'), ('INTERNSHIP', 'internship'), ('OTHERS', 'others')], max_length=80)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('link', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('contacts', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ('-posted_date',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
