# Generated by Django 2.1.2 on 2019-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190308_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('contacts', models.TextField()),
                ('posting_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.TextField()),
            ],
        ),
    ]
