# Generated by Django 2.1.7 on 2019-07-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190308_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_small',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
