# Generated by Django 2.2.9 on 2020-03-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
