# Generated by Django 2.2.9 on 2020-03-26 17:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import obrisk.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200306_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=obrisk.utils.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
