# Generated by Django 2.2.11 on 2020-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200327_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A', 'Article'), ('A', 'Awesome list'), ('C', 'Career'), ('E', 'Event'), ('H', 'How-to-guide'), ('L', 'Lifestyle'), ('N', 'News')], default='A', max_length=1),
        ),
    ]
