# Generated by Django 2.2.5 on 2019-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='key',
            field=models.CharField(default='0000', max_length=64, unique=True),
        ),
    ]
