# Generated by Django 2.2.5 on 2019-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0007_auto_20190923_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
