# Generated by Django 2.2.7 on 2019-11-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0007_auto_20190923_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
