# Generated by Django 2.2.7 on 2019-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0009_message_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classified_thumbnail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
