# Generated by Django 2.2.11 on 2021-08-31 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210831_2134'),
        ('messager', '0010_auto_20191211_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='wx_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WechatMessage',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, max_length=10000, null=True)),
                ('type', models.CharField(choices=[('T', 'Text'), ('P', 'Picture'), ('A', 'Audio'), ('V', 'Video'), ('G', 'Geolocation'), ('L', 'Link'), ('S', 'Short_video'), ('D', 'Documents')], default='T', max_length=1)),
                ('media', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_wx_msgs', to='users.WechatUser', verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'WechatMessage',
                'verbose_name_plural': 'WechatMessages',
                'ordering': ('timestamp',),
            },
        ),
    ]
