# Generated by Django 2.2.9 on 2020-03-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200130_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
