# Generated by Django 2.1.4 on 2019-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_account',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown_city', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Unknown_country', max_length=70, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram account'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
