# Generated by Django 2.1.4 on 2019-01-26 10:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190125_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+8613300000000', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Unknown_country', max_length=50, verbose_name='Country'),
        ),
    ]
