# Generated by Django 2.1.4 on 2019-02-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190126_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province_region',
            field=models.CharField(default='Zhejiang', max_length=100, verbose_name='Province/Region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Hangzhou', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='China', max_length=100, verbose_name='Country'),
        ),
    ]
