# Generated by Django 2.2 on 2019-04-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190319_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Hangzhou', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='China', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province_region',
            field=models.CharField(default='Zhejiang', max_length=100, verbose_name='Province/Region'),
        ),
    ]
