# Generated by Django 2.1.7 on 2019-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190507_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='snapchat_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Snapchat a/c profile name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook a/c profile name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram a/c profile name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LinkedIn a/c profile name'),
        ),
    ]
