# Generated by Django 2.1.7 on 2019-05-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190418_1011'),
        ('users', '0008_auto_20190507_2207'),
    ]

    operations = [
    ]
