# Generated by Django 2.2.5 on 2019-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_org_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='classifieds_transactions_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_classifieds_negotiated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_classifieds_posted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_events_registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_jobs_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_jobs_posted',
            field=models.IntegerField(default=0),
        ),
    ]

