# Generated by Django 2.2.7 on 2019-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191118_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province_region',
            field=models.CharField(max_length=200, verbose_name='Province'),
        ),
    ]
