# Generated by Django 2.2.7 on 2020-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chatting',
            field=models.IntegerField(default=0),
        ),
    ]
