# Generated by Django 2.2.7 on 2020-01-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_is_chatting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_chatting',
        ),
    ]
