# Generated by Django 2.2.11 on 2021-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='english_address',
        ),
        migrations.AddField(
            model_name='user',
            name='chinese_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
