# Generated by Django 2.2.11 on 2021-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210627_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wechat name'),
        ),
    ]
