# Generated by Django 2.2.5 on 2019-10-08 07:22

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('stories', '0002_auto_20190809_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(max_length=400),
        ),
        migrations.AddField(
            model_name='stories',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='province_region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='viewers',
            field=models.CharField(choices=[('P', 'Public'), ('N', 'near-by'), ('C', 'Connects')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='TaggedStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Stories')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_taggedstories_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('image_thumb', models.CharField(max_length=300)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.Stories')),
            ],
        ),
        migrations.AddField(
            model_name='stories',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='stories.TaggedStories', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
