# Generated by Django 2.2.5 on 2019-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20191008_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='thread_count',
            field=models.IntegerField(default=0),
        ),
    ]
