# Generated by Django 2.2.5 on 2019-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20191008_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stories',
            name='thread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
