# Generated by Django 2.2.5 on 2019-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20191031_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='viewers',
            field=models.CharField(choices=[('P', 'Public'), ('A', 'around'), ('C', 'Connects')], default='P', max_length=1),
        ),
    ]
