# Generated by Django 2.2.9 on 2020-03-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200130_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='new_tags',
        ),
        migrations.RemoveField(
            model_name='taggedstory',
            name='tag',
        ),
    ]
