# Generated by Django 2.2.7 on 2020-01-23 08:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200123_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storytags',
            options={'verbose_name': 'Story Tag', 'verbose_name_plural': 'Story Tags'},
        ),
        migrations.AddField(
            model_name='taggedstory',
            name='tags',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stories_taggedstory_items', to='stories.StoryTags'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stories',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='stories.TaggedStory', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedstory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_taggedstory_items', to='taggit.Tag'),
        ),
    ]
