# Generated by Django 2.2.9 on 2020-03-01 11:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20200301_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedstory',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='stories',
            name='new_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='stories.TaggedStory', to='stories.StoryTags', verbose_name='Tags'),
        ),
    ]
