# Generated by Django 2.2.9 on 2020-03-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20200301_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='tags',
        ),
    ]
