# Generated by Django 2.2.9 on 2020-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20200306_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='user_tags',
            field=models.BooleanField(default=False, verbose_name='User created tags?'),
        ),
    ]
