# Generated by Django 2.2.11 on 2020-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_stories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='images_count',
            field=models.IntegerField(default=0),
        ),
    ]
